### PR TITLE
switch from webpack to swc

### PR DESCRIPTION
**Pull request by erikyo**

### CODE REVIEW

**Comment by erikyo** [comment]
ATM everything works except umd export. don't know, suggestions? @johnhooks do you think i should export `* as default` in index.ts to get it working? or do you think i am missing something? umd module is necessary to run this package in the browser I would not want to leave it behind, any suggestion?

--- edited ---
an additional idea can be to export the script for the browser as 
`globalthis.isoToLanguage = {...}`

**Review by johnhooks — APPROVED** [review]
LGTM!

**Comment by erikyo** [comment]
Ha! you haven't seen the last changes :P 

i managed to build the optimized version for ESM - CJS - UMD - browser only, I just have to look into it later because I have to figure out how to make a single export that works for everything. maybe making a glue file as I wrote before is the best solution

that because i can export in this way

```js
globalThis.isoToLanguage = {
    format : format,
    getAll : getAll,
    getAllLanguageCodesByISO : getAllLanguageCodesByISO,
    getAllLanguagesByISO : getAllLanguagesByISO,
    getCountriesByISO : getCountriesByISO,
  ...
}
```

and for the browser the functions will be available under `window` like window.isoToLanguage.getAll()

and in this way

```js
globalThis.format = format;
globalThis.getAll = getAll;
globalThis.getAllLanguageCodesByISO = getAllLanguageCodesByISO;
globalThis.getAllLanguagesByISO = getAllLanguagesByISO;
globalThis.getCountriesByISO = getCountriesByISO;
globalThis.getCountriesByLanguage = getCountriesByLanguage;
  ...
```

and for the browser the functions will be available under `window` like window.getAll(). Would be cool but in this case some functions needs to be renamed to avoid potential collisions with other plugins (e.g. moment)

**Comment by erikyo** [comment]
i need to type the umd/browser scripts in this way 👇 and exclude from swc the `./src/isoToLanguage.ts` and we are ready to go.
```
declare global {
  function myFunction(): boolean;
  var myVariable: number;
}
```

**Pull request merged**
