### PR TITLE
fix ESM imports

### LINKED ISSUE #7: Cannot find module '/node_modules/ISOToLanguage/lib/esm/index.js'
Very nice project, thank you!  ❤️ 
I noticed 2 things, though:

1. "Weighing less than 10kb gzipped" seems incorrect. Everywhere it says 2mb.
2. I can't import it:

```haskell
Error: Cannot find module '/services/whatsapp-listener/node_modules/ISOToLanguage/lib/esm/index.js' imported from /services/whatsapp-listener/context.ts
    at finalizeResolution (/node_modules/.pnpm/ts-node@10.9.2_@types+node@20.11.24/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:366:11)
    at moduleResolve (/node_modules/.pnpm/ts-node@10.9.2_@types+node@20.11.24/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:801:10)
    at Object.defaultResolve (/node_modules/.pnpm/ts-node@10.9.2_@types+node@20.11.24/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
    at /node_modules/.pnpm/ts-node@10.9.2_@types+node@20.11.24/node_modules/ts-node/src/esm.ts:218:35
    at entrypointFallback (/node_modules/.pnpm/ts-node@10.9.2_@types+node@20.11.24/node_modules/ts-node/src/esm.ts:168:34)
    at /node_modules/.pnpm/ts-node@10.9.2_@types+node@20.11.24/node_modules/ts-node/src/esm.ts:217:14
    at addShortCircuitFlag (/node_modules/.pnpm/ts-node@10.9.2_@types+node@20.11.24/node_modules/ts-node/src/esm.ts:409:21)
    at resolve (/node_modules/.pnpm/ts-node@10.9.2_@types+node@20.11.24/node_modules/ts-node/src/esm.ts:197:12)
    at nextResolve (node:internal/modules/esm/hooks:865:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:303:30)
    ```

### PR DESCRIPTION
**Pull request by zvictor**
fix #7

### CODE REVIEW

**Comment by zvictor** [comment]
wait?! Am I the first external contributor?

many more will come!

**Comment by erikyo** [comment]
yes, but actually you are only the first one of a long series 😛

good catch! In the last version I exported esm as mjs and commonjs as cjs but then I forgot to update package.json

can i ask you to update the extension for commonjs as well? thanks!

**Comment by zvictor** [comment]
Done! Thank you

**Comment by erikyo** [comment]
[Published](https://www.npmjs.com/package/isotolanguage/v/1.2.3)! Thank you again!

**Comment by zvictor** [comment]
This is not the ideal place for asking questions, but in the lack of a `Discussions` tab let me try it here...

I have noticed that `languages` seem to sort the spoken languages by popularity. E.g. in Spain it lists Spanish before Catalan (which would be first, alphabetically).

That's a great feature! Is this guaranteed somehow or was just a coincidence?

```json
  "VA": {
    "languages": [
      "it",
      "la"
    ],
    "name": "Vatican City",
    "original": "Vaticano",
    "iso3": "VAT"
  }
  ```

**Comment by erikyo** [comment]
ah, do you know what... I didn't realise that! HAHA very cool feature 😅

I gathered those dataset from the original websites (like this one https://www.loc.gov/standards/iso639-5/id.php), i wrote a parser and created the json with the table... then mixed the "relevant" data into in the ones you see that I published, after doing some cleanup.

I have not sorted them again, so I believe they are still in the original order in which they were, probably as you mentioned in a "popularity" order.

**Comment by zvictor** [comment]
Cool! That's a great feature, indeed!

The use case that brought me to this library is that I need to set the default language my AI agents will use when talking to new customers (https://divino.ai).

Without your library the agents would be now speaking catalan with the spaniards 🥲

**Comment by erikyo** [comment]
🎉i am glad that it is useful, and especially that it is useful for something it was not designed for. 

I guess the datasets are definitely complete now but i need to work on utility functions to make the best use of that data that i gathered and cross-reference those data to obtain complex datasets.

if you have any advice or ideas i'm open to suggestions!

**Pull request merged**
